name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pravtz/node-ts-api-stress

      - name: Copy DockerHub documentation
        run: cp DOCKERHUB.md ./README.md

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install jq and curl
        run: sudo apt-get install -y jq curl

      - name: Update DockerHub description
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          DESCRIPTION=$(cat DOCKERHUB.md)
          REPO_NAME=pravtz/node-ts-api-stress
          curl -s -X PATCH "https://hub.docker.com/v2/repositories/$REPO_NAME/" \
          -H "Content-Type: application/json" \
          -H "Authorization: JWT $(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${DOCKERHUB_USERNAME}", "password": "${DOCKERHUB_TOKEN}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)" \
          -d "{\"full_description\": \"${DESCRIPTION}\"}"
